[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "[...] script-src https://netlify-rum.netlify.app"

[[plugins]]
package = "node_modules/.bin/sentry-netlify-build-plugin"
